[package]
name = "ysm"
version = "0.1.0"
authors = ["Karol Belina <karolbelina@gmail.com>"]
edition = "2018"

[dependencies]
codespan-reporting = "0.11.1"
nom = "6.1.2"
structopt = "0.3.21"
unicode-segmentation = "1.6.0"
